export enum BtNames {
  BT1 = 'BT-01: Booster New Evolution',
  BT2 = 'BT-02: Booster Ultimate Power',
  BT3 = 'BT-03: Booster Union Impact',
  BT4 = 'BT-04: Booster Great Legend',
  BT5 = 'BT-05: Booster Battle Of Omni',
  BT6 = 'BT-06: Booster Double Diamond',
  BT7 = 'BT-07: Booster Next Adventure',
  BT8 = 'BT-08: Booster New Awakening',
  BT9 = 'BT-09: Booster X Record',
  BT10 = 'BT-10: Booster Xros Encounter',
  BT11 = 'BT-11: Booster Dimensional Phase',
  BT12 = 'BT-12: Booster Across Time',
  BT13 = 'BT-13: Booster Versus Royal Knights',
  BT14 = 'BT-14: Booster Blast Ace',
  BT15 = 'BT-15: Booster Exceed Apocalypse',
  BT16 = 'BT-16: Booster Beginning Observer',
  BT17 = 'BT-17: Booster Secret Crisis',
  BT18 = 'BT-18: Booster Elemental Successor',
  BT19 = 'BT-19: Booster Xros Evolution',
  BT20 = 'BT-20: Booster Over the X',
  BT21 = 'BT-21: Booster World Convergence',
}
